name: demo_app
description: "**demo-app**   A Flutter app with endless scrolling magic! Loop through albums and photos seamlessly—vertically and horizontally. Powered by BLoC, cached for speed, and built for fun."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  hive: ^2.2.3
  hive_flutter:
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  flutter_native_splash: ^2.4.3
  get_it: ^8.0.2
  get: ^4.6.6
  device_info_plus: ^11.1.1
  connectivity_plus:
  dartz:
  dio:
  collection:
  shimmer: ^3.0.0
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  flutter_cache_manager:
  infinite_listview: ^1.1.0
  loop_page_view: ^1.2.5
  injectable: ^2.5.0
  retrofit: ^4.4.1
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  injectable_generator:
  retrofit_generator: '>=8.0.0 <10.0.0'
  build_runner:
  flutter_lints: ^5.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
